import base64
import io
from datetime import datetime

from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import PlainTextResponse
from fastapi.staticfiles import StaticFiles
from PIL import Image

import database
import inference

app = FastAPI(title="Brain MRI Screening API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

database.init_db()


def make_thumbnail(image_bytes: bytes, size=(160, 160)) -> str:
    try:
        img = Image.open(io.BytesIO(image_bytes)).convert("L").convert("RGB")
        img.thumbnail(size)
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=70)
        return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()
    except Exception:
        return ""


@app.post("/api/predict")
async def predict(file: UploadFile = File(...), patient_label: str = Form(default="")):
    image_bytes = await file.read()
    try:
        result = inference.run_pipeline(image_bytes)
    except inference.InvalidImageError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Inference failed: {e}")

    thumb = make_thumbnail(image_bytes)
    scan_id = database.save_scan(file.filename, patient_label, result, thumb)
    return {"id": scan_id, "filename": file.filename, "patient_label": patient_label, **result}


@app.get("/api/history")
async def history(limit: int = 100):
    return database.list_scans(limit=limit)


@app.get("/api/history/{scan_id}")
async def history_detail(scan_id: int):
    scan = database.get_scan(scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")
    return scan


@app.get("/api/stats")
async def stats():
    return database.stats_summary()


@app.get("/api/history/{scan_id}/report", response_class=PlainTextResponse)
async def report(scan_id: int):
    scan = database.get_scan(scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")
    r = scan["result"]
    lines = []
    lines.append("=" * 60)
    lines.append("BRAIN MRI AI SCREENING REPORT (RESEARCH USE ONLY)")
    lines.append("=" * 60)
    lines.append(f"Scan ID: {scan['id']}")
    lines.append(f"File: {scan['filename']}")
    lines.append(f"Patient / Label: {scan['patient_label'] or 'N/A'}")
    lines.append(f"Date: {datetime.fromtimestamp(scan['created_at']).strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("-" * 60)
    lines.append("STAGE 1 — Tumor Screening")
    s1 = r["stage1"]
    lines.append(f"  Tumor probability : {s1['probability_tumor']}")
    lines.append(f"  Decision threshold: {s1['decision_threshold']}")
    lines.append(f"  Tumor detected    : {s1['tumor_detected']}")
    lines.append(f"  Out of distribution flag: {s1['out_of_distribution']}")
    if r["stage2"]:
        lines.append("-" * 60)
        lines.append("STAGE 2 — Tumor Subtype Classification")
        s2 = r["stage2"]
        for cls, p in s2["class_probabilities"].items():
            lines.append(f"  {cls:<12}: {p}")
        lines.append(f"  Predicted class   : {s2['predicted_class']}")
        lines.append(f"  Confidence        : {s2['confidence']}")
        lines.append(f"  Out of distribution flag: {s2['out_of_distribution']}")
    lines.append("-" * 60)
    lines.append(f"FINAL VERDICT: {r['final_verdict']}")
    lines.append("=" * 60)
    lines.append("DISCLAIMER: This output is generated by an AI research model.")
    lines.append("It is NOT a medical diagnosis and has NOT been validated for")
    lines.append("clinical use. Always consult a qualified radiologist / physician.")
    lines.append("=" * 60)
    return "\n".join(lines)


# Serve the frontend (must be mounted last so /api routes take priority)
app.mount("/", StaticFiles(directory="../frontend", html=True), name="frontend")
